In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
double_arr = arr + arr
double_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
half_arr = arr - arr
half_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
square_arr = arr * arr
square_arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [13]:
hundred_arr = arr + 100
hundred_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [17]:
np.array(100).shape

()

In [20]:
1/0

ZeroDivisionError: division by zero

In [21]:
# 0/0 will give a Null Object back in NumPy & gives a warning
arr / arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
# 1/ 0 will give Infinity
1/ arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [24]:
sq_arr = arr ** 2
sq_arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [27]:
# Universal Function for calculating Square Root in NumPy
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [28]:
# Universal Function for calculating Exponential in NumPy
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [30]:
# Universal Function for getting Max in NumPy
arr.max()

10

In [32]:
# Universal Function for getting Min in NumPy
arr.min()

0

In [33]:
# Universal Function for calculating Sine in NumPy
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [34]:
# Universal Function for calculating Log in NumPy
np.log(arr)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [35]:
# Universal Function for calculating Mean in NumPy
np.mean(arr)

5.0