In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [6]:
# Converting a list to numpy array using np.array()
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [5]:
type(np.array(my_list))

numpy.ndarray

In [8]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# arange() to give a list of numbers similar to range() in Python
np.arange(0, 10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# arange() to give a list of numbers with step-size similar to range() in Python
np.arange(0, 11, 2) 

array([ 0,  2,  4,  6,  8, 10])

In [16]:
# Get all zeroes in Numpy Array, specify count as parameter which can be int or a tuple
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# Get all ones in Numpy Array, specify count as parameter which can be int or a tuple
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# To get a particular number of evenly spaced points between 2 numbers
np.linspace(0, 5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [27]:
# Creates an Identity Matrix - A Matrix with diagonal as 1 and remaining 0 with size as parameter
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# Creates a 1-D Array populated with Random Numbers from 0 - 1
np.random.rand(5)

array([0.36784424, 0.86219238, 0.39252797, 0.17879406, 0.69738266])

In [31]:
# Creates a 2-D Array populated with Random Numbers from 0 - 1, note here we are passing a Tuple
np.random.rand(5, 5)

array([[0.571325  , 0.84060294, 0.94451362, 0.14741507, 0.44761887],
       [0.14215454, 0.75519791, 0.81726772, 0.71457094, 0.33243856],
       [0.81055362, 0.64363124, 0.09351818, 0.71318195, 0.83379974],
       [0.47709985, 0.73885951, 0.04372225, 0.40014567, 0.27182712],
       [0.91948204, 0.44036275, 0.59902794, 0.6955654 , 0.36408317]])

In [33]:
# Creates a 1-D Array populated with Random Numbers from Standard Normal Distribution
np.random.randn(2)

array([0.9574639 , 1.23809382])

In [35]:
# Creates a 2-D Array populated with Random Numbers from Standard Normal Distribution, note here we are passing a Tuple
np.random.randn(4, 4)

array([[ 1.16377576, -0.88986169, -0.59293936, -0.90300378],
       [ 0.9944513 , -1.02777753, -1.15014549, -0.42053839],
       [ 0.75411496, -0.20976199,  0.44026377,  0.42827931],
       [-0.45408106, -1.38612652, -0.78227628, -0.95554243]])

In [36]:
# Creates an array of Random Integers between a particular Range
np.random.randint(1, 100)

93

In [37]:
# Creates an array Particular Number of Random Integers between a particular Range
np.random.randint(1, 100, 10)

array([74, 91, 30, 18, 27,  4, 71, 43, 98, 81])

In [38]:
# Creates an array Particular Size of Random Integers between a particular Range
np.random.randint(1, 100, (10, 10))

array([[13, 52, 85, 48, 63, 34, 76, 26, 20, 67],
       [21, 35, 18, 55, 60, 25, 69, 48, 89, 76],
       [74,  4, 64, 62, 42, 47, 78, 82, 77,  8],
       [99, 87, 62, 72, 39, 49, 67, 92, 19, 76],
       [ 8, 91, 52, 98, 85, 28, 65, 89, 23, 72],
       [ 8, 28, 69, 15, 51, 59, 24, 91, 25, 40],
       [66, 78,  3, 10, 63, 25, 98, 37, 53, 53],
       [50,  8, 63, 75, 14, 74, 49, 21, 89, 58],
       [80, 67, 78, 62, 10, 47,  8, 21, 93, 80],
       [78, 64, 98, 35, 82, 12,  1, 66, 79, 63]])

In [39]:
arr = np.arange(25)

In [41]:
randarr = np.random.randint(0, 50, 10)

In [44]:
# Reshape the Array by passing No. of Rows & Columns we want
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
randarr

array([13, 40, 33, 31, 45, 40, 26, 14,  3, 16])

In [46]:
# Returns the Max value out of NumPy Array
randarr.max()

45

In [47]:
# Returns the Min value out of NumPy Array
randarr.min()

3

In [50]:
# Returns the Index Location of the Desired Max
randarr.argmax()

4

In [51]:
# Returns the Index Location of the Desired Min
randarr.argmin()

8

In [54]:
# Returns Shape of the NumPy Array
arr.shape

(25,)

In [55]:
arr.reshape(5, 5).shape

(5, 5)

In [56]:
# Returns Datatupe of the NumPy Array
arr.dtype

dtype('int32')

In [57]:
# arr.shape and arr.dtype haven't got Paranthesis at the end

In [59]:
from numpy.random import randint

In [60]:
randint(0, 10, (2, 5))

array([[0, 1, 0, 3, 6],
       [0, 7, 4, 0, 6]])